# Generated by Django 5.2.10 on 2026-02-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('inviter_id', models.BigIntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('rejoin_count', models.IntegerField(default=0)),
                ('is_fake', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inviteslog',
            },
        ),
    ]
